### ISSUE TITLE
database url

### ISSUE THREAD

**Issue by johnyserpa** [AskalotCQA/askalot#5]
Hey, I'm trying to dockerize your app, but wondering where to set database host param.
Thanks!

**Comment by adrianhuna** [comment]
Hello @johnyserpa,

the database connection should be set in `config/database.yml` -> we provide `config.database.yml.example` file with example configuration.

Please also note installation instructions in README:

```
...

Copy and edit configuration files.

cp config/configuration.{yml.example,yml}
cp config/database.{yml.example,yml}
cp config/newrelic.{yml.example,yml}
...
```

**Comment by johnyserpa** [comment]
Sorry for the lateness.

I did see the conf file but did not understand where to put the host value.

```
fiit_development:
  adapter: postgresql
  encoding: unicode
  database: askalot_fiit_development
  pool: 5
  username: postgres
  password: postgres
```
